version: '3.4'

services:
  db:
    image: mysql:5.7
    ports: 
      - "3307:3306"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
    volumes:
       - dbdata:/var/lib/mysql
    restart: always

  inventoryapi:
    depends_on:
        - db
        - rabbitmq
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: InventoryAPI/Dockerfile
    ports:
      - "5001:80"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    #volumes:
      #- ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #- ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      #- ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      #- ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

volumes:
    dbdata:

networks:
    my-network: 
        driver: bridge